#!/bin/sh

if [ -x /usr/bin/gtk-update-icon-cache ]; then
  /usr/bin/gtk-update-icon-cache -f /usr/share/icons/hicolor
fi

if ps -e | grep gconfd-2 > /dev/null; then
  killall gconfd-2
fi

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
	gconftool-2 --makefile-install-rule /etc/gconf/schemas/panucci.schemas
killall gconfd-2

#DEBHELPER#

